package io.github.hectorvent.floci.core.common;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

/**
 * Every IAM service namespace, read once from the vendored {@code aws/iam-service-namespaces.json}.
 *
 * <p>The file is generated by {@code tools/aws/regen_service_namespaces.py} from AWS's Service
 * Reference Information index (https://servicereference.us-east-1.amazonaws.com/), whose per-service
 * {@code service} field is the IAM namespace itself. botocore is deliberately not the source: a
 * namespace is not any botocore field, since CloudWatch's {@code endpointPrefix} is {@code
 * monitoring} and its {@code serviceId} is {@code CloudWatch} against an IAM namespace of {@code
 * cloudwatch}. {@code make iam-namespaces-verify} checks that nothing here is invented.
 *
 * <p>This exists so a policy that grants a service without naming it can still be reported on:
 * {@code "Action": "*"} and a globbed prefix such as {@code s3*} name no namespace, so
 * {@code GetServiceLastAccessedDetails} needs a list to expand them against.
 *
 * <p>A missing or malformed resource is a build defect, not a runtime condition, so loading fails
 * with {@link IllegalStateException} rather than degrading to an empty catalog, which would
 * silently turn every wildcard grant back into an unreported one.
 */
public final class AwsServiceNamespaces {

    static final String RESOURCE_NAME = "aws/iam-service-namespaces.json";

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private static final class Holder {
        static final List<String> NAMESPACES = load();
    }

    private AwsServiceNamespaces() {
    }

    /**
     * Every published namespace, sorted, as the vendored file lists them.
     *
     * <p>Matching a globbed pattern against these is the caller's job, so that the one glob
     * implementation Floci already has for policy patterns stays in the IAM evaluator rather than
     * being duplicated here.
     */
    public static List<String> all() {
        return Holder.NAMESPACES;
    }

    private static List<String> load() {
        try (InputStream in = Thread.currentThread().getContextClassLoader().getResourceAsStream(RESOURCE_NAME)) {
            if (in == null) {
                throw new IllegalStateException("IAM service namespace catalog resource not found: "
                        + RESOURCE_NAME);
            }
            return parse(in);
        } catch (IOException e) {
            throw new IllegalStateException("Failed to read the IAM service namespace catalog "
                    + RESOURCE_NAME, e);
        }
    }

    static List<String> parse(InputStream in) throws IOException {
        JsonNode root = MAPPER.readTree(in);
        JsonNode namespaces = root.path("serviceNamespaces");
        if (!namespaces.isArray() || namespaces.isEmpty()) {
            throw new IllegalStateException(RESOURCE_NAME + " carries no serviceNamespaces");
        }
        List<String> parsed = new ArrayList<>(namespaces.size());
        for (JsonNode namespace : namespaces) {
            String value = namespace.asText("");
            if (value.isBlank()) {
                throw new IllegalStateException(RESOURCE_NAME + " carries a blank service namespace");
            }
            parsed.add(value);
        }
        return List.copyOf(parsed);
    }
}
